from fastapi import FastAPI, Depends, HTTPException
from sqlalchemy import text
from sqlalchemy.orm import Session
from app.database import engine, get_db
from app import models, schemas

models.Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="Dashboard API",
    description="Backend for personal SaaS dashboard",
    version="0.1.0"
)

# --- NEW ENDPOINT ---
@app.post("/users/", response_model=schemas.UserResponse)
def create_user(user: schemas.UserCreate, db: Session = Depends(get_db)):
    # 1. Check if a user with this email already exists
    db_user = db.query(models.User).filter(models.User.email == user.email).first()
    if db_user:
        raise HTTPException(status_code=400, detail="Email already registered")
    
    # 2. "Hash" the password (Fake hash for now, real cryptography coming next!)
    fake_hashed_password = user.password + "notreallyhashed"
    
    # 3. Create the SQLAlchemy model instance
    new_user = models.User(email=user.email, hashed_password=fake_hashed_password)
    
    # 4. Add to the database session and commit (save)
    db.add(new_user)
    db.commit()
    
    # 5. Refresh to get the new ID and created_at timestamp generated by Postgres
    db.refresh(new_user)
    
    # 6. Return the new user. FastAPI will automatically filter it through UserResponse!
    return new_user
# --------------------

@app.get("/db-test")
def test_db_connection(db: Session = Depends(get_db)):
    try:
        db.execute(text("SELECT 1"))
        return {"status": "success", "message": "Database connected successfully!"}
    except Exception as e:
        return {"status": "error", "message": str(e)}

@app.get("/")
def read_root():
    return {"status": "ok", "message": "Backend is running!"}